//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadDataTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoadDataTest.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games;player
        ///Thresh,17,13,4,76.5,1,2.41,10.47,4.76,46.47,N/A,N/A,N/A,72.5%,6.3%,N/A,Alistar,9,4,5,44.4,0.56,2.22,10.33,4.90,48.22,1.28,N/A,N/A,79%,4%,N/A,Braum,5,0,5,0,0.2,4.6,7,1.57,60.6,1.51,N/A,N/A,64.3%,1.8%,N/A,Bard,4,1,3,25,0.75,2.5,5.75,2.60,24.5,0.67,N/A,N/A,70.3%,8.1%,N/A,Trundle,1,0,1,0,0,4,11,2.75,89,1.88,12.2k,258,84.6%,0%,15.1%,Braum,10,5,5,50,0.6,3.8,11.9,3.29,53.2,1.41,10.33k,273,77.6%,3.7%,15%,Thresh,8,2,6,25,1.5,3.5,9.38,3.11,62.63,1.47,11.21k,263,76.3%,10.5%,14.8%,Karma,5,1,4,20,1,4.6,7.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerPools {
            get {
                return ResourceManager.GetString("PlayerPools", resourceCulture);
            }
        }
    }
}
